=== cdacpune1/AWP/awpsunbeam/Day 10/Students.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="Students">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Student" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Student">
  <mahesh></mahesh>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="No" type="xs:integer"/>
        <xs:element name="Name" type="xs:string"/>
        <xs:element name="Address" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== cdacpune1/AWP/awpsunbeam/Day 10/Students2.xml
<?xml version="1.0" encoding="UTF-8"?>
<Students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
                     xsi:noNamespaceSchemaLocation="/home/osboxes/Desktop/DAC/Students.xsd">
  <Student>
   <No>1</No>  
   <Name>Lalit</Name>
   <Address>Pune</Address>
  </Student>
  <Student>
   <No>2</No>  
   <Name>Jatin</Name>
  <Address>Chennai</Address>
  
  </Student>
</Students>
